import { ChatbotTheme } from "./types";

export const presetThemes: Record<string, ChatbotTheme> = {
  default: {
    preset: "default",
    primary: "#6366f1",
    secondary: "#818cf8",
    background: "#ffffff",
    foreground: "#1f2937",
    chat_bg: "#f3f4f6",
    user_bubble: "#6366f1",
    user_text: "#ffffff",
    bot_bubble: "#e5e7eb",
    bot_text: "#1f2937",
  },
  ocean: {
    preset: "ocean",
    primary: "#0ea5e9",
    secondary: "#38bdf8",
    background: "#f0f9ff",
    foreground: "#0c4a6e",
    chat_bg: "#e0f2fe",
    user_bubble: "#0ea5e9",
    user_text: "#ffffff",
    bot_bubble: "#bae6fd",
    bot_text: "#0c4a6e",
  },
  forest: {
    preset: "forest",
    primary: "#16a34a",
    secondary: "#4ade80",
    background: "#f0fdf4",
    foreground: "#14532d",
    chat_bg: "#dcfce7",
    user_bubble: "#16a34a",
    user_text: "#ffffff",
    bot_bubble: "#bbf7d0",
    bot_text: "#14532d",
  },
  sunset: {
    preset: "sunset",
    primary: "#f97316",
    secondary: "#fb923c",
    background: "#fff7ed",
    foreground: "#7c2d12",
    chat_bg: "#ffedd5",
    user_bubble: "#f97316",
    user_text: "#ffffff",
    bot_bubble: "#fed7aa",
    bot_text: "#7c2d12",
  },
  midnight: {
    preset: "midnight",
    primary: "#8b5cf6",
    secondary: "#a78bfa",
    background: "#0f172a",
    foreground: "#e2e8f0",
    chat_bg: "#1e293b",
    user_bubble: "#8b5cf6",
    user_text: "#ffffff",
    bot_bubble: "#334155",
    bot_text: "#e2e8f0",
  },
  rose: {
    preset: "rose",
    primary: "#e11d48",
    secondary: "#fb7185",
    background: "#fff1f2",
    foreground: "#881337",
    chat_bg: "#ffe4e6",
    user_bubble: "#e11d48",
    user_text: "#ffffff",
    bot_bubble: "#fecdd3",
    bot_text: "#881337",
  },
  wonderland: {
    preset: "wonderland",
    primary: "#7c3aed",
    secondary: "#a78bfa",
    background: "#faf5ff",
    foreground: "#1e1b4b",
    chat_bg: "#f5f3ff",
    user_bubble: "#7c3aed",
    user_text: "#ffffff",
    bot_bubble: "#ede9fe",
    bot_text: "#1e1b4b",
  },
  corporate: {
    preset: "corporate",
    primary: "#1d4ed8",
    secondary: "#3b82f6",
    background: "#ffffff",
    foreground: "#111827",
    chat_bg: "#f9fafb",
    user_bubble: "#1d4ed8",
    user_text: "#ffffff",
    bot_bubble: "#dbeafe",
    bot_text: "#111827",
  },
  warm: {
    preset: "warm",
    primary: "#d97706",
    secondary: "#fbbf24",
    background: "#fffbeb",
    foreground: "#78350f",
    chat_bg: "#fef3c7",
    user_bubble: "#d97706",
    user_text: "#ffffff",
    bot_bubble: "#fde68a",
    bot_text: "#78350f",
  },
  slate: {
    preset: "slate",
    primary: "#475569",
    secondary: "#64748b",
    background: "#f8fafc",
    foreground: "#1e293b",
    chat_bg: "#f1f5f9",
    user_bubble: "#475569",
    user_text: "#ffffff",
    bot_bubble: "#e2e8f0",
    bot_text: "#1e293b",
  },
};

export const presetThemeNames: { key: string; label: string }[] = [
  { key: "default", label: "Indigo" },
  { key: "ocean", label: "Ocean" },
  { key: "forest", label: "Forest" },
  { key: "sunset", label: "Sunset" },
  { key: "midnight", label: "Midnight" },
  { key: "rose", label: "Rose" },
  { key: "wonderland", label: "Wonderland" },
  { key: "corporate", label: "Corporate" },
  { key: "warm", label: "Warm" },
  { key: "slate", label: "Slate" },
];
